
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BE
{

using System;
    using System.Collections.Generic;
    
public partial class direccion
{

    public int DireccionId { get; set; }

    public string Denominacion { get; set; }

    public string Referencia { get; set; }

    public Nullable<int> PersonaId { get; set; }



    public virtual persona persona { get; set; }

}

}
