
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BE
{

using System;
    using System.Collections.Generic;
    
public partial class imagen
{

    public int imagenId { get; set; }

    public int ArticuloId { get; set; }

    public string Detalle { get; set; }

    public string UrlImagen { get; set; }



    public virtual articulo articulo { get; set; }

}

}
