//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int AlmacenId { get; set; }
        public int ArticuloId { get; set; }
        public int Cantidad { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual almacen almacen { get; set; }
        public virtual articulo articulo { get; set; }
    }
}
