
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BE
{

using System;
    using System.Collections.Generic;
    
public partial class movimiento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public movimiento()
    {

        this.movimientodet = new HashSet<movimientodet>();

    }


    public int MovimientoId { get; set; }

    public int AlmacenId { get; set; }

    public string Tipo { get; set; }

    public string Operacion { get; set; }

    public string Estado { get; set; }

    public int PersonaId { get; set; }

    public System.DateTime Fecha { get; set; }

    public decimal SubTotal { get; set; }

    public decimal IGV { get; set; }

    public decimal Ajuste { get; set; }

    public decimal Total { get; set; }

    public string Glosa { get; set; }

    public string Documento { get; set; }



    public virtual almacen almacen { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<movimientodet> movimientodet { get; set; }

    public virtual persona persona { get; set; }

}

}
