//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidodet
    {
        public int PedidodetId { get; set; }
        public Nullable<int> PedidoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> ArticuloId { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
