
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BE
{

using System;
    using System.Collections.Generic;
    
public partial class persona
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public persona()
    {

        this.direccion = new HashSet<direccion>();

        this.movimiento = new HashSet<movimiento>();

        this.usuario = new HashSet<usuario>();

    }


    public int PersonaId { get; set; }

    public string Tipo { get; set; }

    public string Nombres { get; set; }

    public string Paterno { get; set; }

    public string Materno { get; set; }

    public string TipoDocumento { get; set; }

    public string NroDocumento { get; set; }

    public string Celular { get; set; }

    public string Correo { get; set; }

    public string Sexo { get; set; }

    public Nullable<System.DateTime> FechaNacimiento { get; set; }

    public bool Estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<direccion> direccion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<movimiento> movimiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<usuario> usuario { get; set; }

}

}
